files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore: 'src/sass/foxlight.sass'
rules:
  indentation: 0 # Turn this on once node-sass bugs are fixed
  no-vendor-prefixes: 2
  property-sort-order: 0
  no-ids: 1 # Just a warning
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  quotes:
    - 2
    -
      style: single
  empty-line-between-blocks: 0
  brace-style: 0
  single-line-per-selector: 0
  leading-zero: 0
  shorthand-values: 0
  final-newline: 0 # This should be 2, but is currently buggy
